In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,10.0,2.0,14.6,1.0,0.0,0.0,2023,Arsenal
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,Match Report,NaN,19.0,7.0,13.0,0.0,0.0,0.0,2023,Arsenal
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,Match Report,NaN,14.0,6.0,14.8,0.0,0.0,0.0,2023,Arsenal
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,Match Report,NaN,22.0,8.0,15.5,1.0,0.0,0.0,2023,Arsenal
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,22.0,8.0,16.3,1.0,0.0,0.0,2023,Arsenal

In [4]:
matches.shape

(4052, 27)

In [5]:
matches["team"].value_counts()

Everton                     203
West Ham United             203
Tottenham Hotspur           203
Leicester City              203
Southampton                 203
Newcastle United            203
Brighton and Hove Albion    202
Manchester City             202
Manchester United           202
Chelsea                     202
Liverpool                   202
Arsenal                     202
Crystal Palace              202
Burnley                     190
Wolverhampton Wanderers     165
Watford                     152
Aston Villa                 127
Bournemouth                 127
Fulham                       89
Leeds United                 88
West Bromwich Albion         76
Huddersfield Town            76
Sheffield United             76
Norwich City                 76
Brentford                    51
Cardiff City                 38
Swansea City                 38
Stoke City                   38
Nottingham Forest            13
Name: team, dtype: int64

In [6]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2017-08-12,12:30,Premier League,Matchweek 1,Sat,Away,D,3.0,3.0,Watford,...,Match Report,NaN,13.0,4.0,13.9,0.0,1.0,1.0,2018,Liverpool
2,2017-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,23.0,13.0,18.6,2.0,0.0,0.0,2018,Liverpool
4,2017-08-27,16:00,Premier League,Matchweek 3,Sun,Home,W,4.0,0.0,Arsenal,...,Match Report,NaN,18.0,10.0,15.9,0.0,0.0,0.0,2018,Liverpool
5,2017-09-09,12:30,Premier League,Matchweek 4,Sat,Away,L,0.0,5.0,Manchester City,...,Match Report,NaN,7.0,3.0,20.5,2.0,0.0,0.0,2018,Liverpool
7,2017-09-16,15:00,Premier League,Matchweek 5,Sat,Home,D,1.0,1.0,Burnley,...,Match Report,NaN,35.0,9.0,20.6,0.0,0.0,0.0,2018,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,2022-10-09,16:30,Premier League,Matchweek 10,Sun,Away,L,2.0,3.0,Arsenal,...,Match Report,NaN,8.0,3.0,18.0,0.0,0.0,0.0,2023,Liverpool
13,2022-10-16,16:30,Premier League,Matchweek 11,Sun,Home,W,1.0,0.0,Manchester City,...,Match Report,NaN,13.0,2.0,17.5,0.0,0.0,0.0,2023,Liverpool
14,2022-10-19,19:30,Premier League,Matchweek 12,Wed,Home,W,1.0,0.0,West Ham,...,Match Report,NaN,22.0,7.0,17.5,0.0,0.0,0.0,2023,Liverpool
15,2022-10-22,12:30,Premier League,Matchweek 13,Sat,Away,L,0.0,1.0,Nott'ham Forest,...,Match Report,NaN,15.0,7.0,10.4,0.0,0.0,0.0,2023,Liverpool
17,2022-10-29,19:45,Premier League,Matchweek 14,Sat,Home,L,1.0,2.0,Leeds United,...,Match Report,NaN,22.0,10.0,16.4,0.0,0.0,0.0,2023,Liverpool

In [7]:
matches["round"].value_counts()

Matchweek 3     120
Matchweek 1     120
Matchweek 4     120
Matchweek 13    120
Matchweek 11    120
Matchweek 10    120
Matchweek 2     120
Matchweek 5     120
Matchweek 14    120
Matchweek 6     120
Matchweek 9     120
Matchweek 12    118
Matchweek 8     114
Matchweek 33    100
Matchweek 27    100
Matchweek 29    100
Matchweek 16    100
Matchweek 18    100
Matchweek 22    100
Matchweek 17    100
Matchweek 31    100
Matchweek 38    100
Matchweek 26    100
Matchweek 7     100
Matchweek 35    100
Matchweek 34    100
Matchweek 28    100
Matchweek 36    100
Matchweek 30    100
Matchweek 23    100
Matchweek 19    100
Matchweek 37    100
Matchweek 25    100
Matchweek 15    100
Matchweek 20    100
Matchweek 24    100
Matchweek 21    100
Matchweek 32    100
Name: round, dtype: int64

In [8]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [9]:
del matches["comp"]

In [10]:
del matches["notes"]

In [11]:
matches["date"] = pd.to_datetime(matches["date"])

In [12]:
matches["target"] = (matches["result"] == "W").astype("int")

In [13]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
0,2022-08-05,20:00,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,1.0,...,Match Report,10.0,2.0,14.6,1.0,0.0,0.0,2023,Arsenal,1
1,2022-08-13,15:00,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,2.7,...,Match Report,19.0,7.0,13.0,0.0,0.0,0.0,2023,Arsenal,1
2,2022-08-20,17:30,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,1.3,...,Match Report,14.0,6.0,14.8,0.0,0.0,0.0,2023,Arsenal,1
3,2022-08-27,17:30,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,2.6,...,Match Report,22.0,8.0,15.5,1.0,0.0,0.0,2023,Arsenal,1
4,2022-08-31,19:30,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,2.4,...,Match Report,22.0,8.0,16.3,1.0,0.0,0.0,2023,Arsenal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2018-04-15,16:00,Matchweek 34,Sun,Away,W,1.0,0.0,Manchester Utd,0.7,...,Match Report,10.0,4.0,18.1,0.0,0.0,0.0,2018,West Bromwich Albion,1
39,2018-04-21,12:30,Matchweek 35,Sat,Home,D,2.0,2.0,Liverpool,1.3,...,Match Report,13.0,6.0,17.7,0.0,0.0,0.0,2018,West Bromwich Albion,0
40,2018-04-28,15:00,Matchweek 36,Sat,Away,W,1.0,0.0,Newcastle Utd,0.7,...,Match Report,9.0,2.0,20.1,0.0,0.0,0.0,2018,West Bromwich Albion,1
41,2018-05-05,15:00,Matchweek 37,Sat,Home,W,1.0,0.0,Tottenham,1.6,...,Match Report,9.0,1.0,10.2,0.0,0.0,0.0,2018,West Bromwich Albion,1
42,2018-05-13,15:00,Matchweek 38,Sun,Away,L,0.0,2.0,Crystal Palace,0.2,...,Match Report,7.0,1.0,24.8,1.0,0.0,0.0,2018,West Bromwich Albion,0

In [14]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [15]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [16]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [17]:
matches["day_code"] = matches["date"].dt.dayofweek

In [18]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2022-08-05,20:00,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,1.0,...,1.0,0.0,0.0,2023,Arsenal,1,0,8,20,4
1,2022-08-13,15:00,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,2.7,...,0.0,0.0,0.0,2023,Arsenal,1,1,13,15,5
2,2022-08-20,17:30,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,1.3,...,0.0,0.0,0.0,2023,Arsenal,1,0,2,17,5
3,2022-08-27,17:30,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,2.6,...,1.0,0.0,0.0,2023,Arsenal,1,1,10,17,5
4,2022-08-31,19:30,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,2.4,...,1.0,0.0,0.0,2023,Arsenal,1,1,1,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2018-04-15,16:00,Matchweek 34,Sun,Away,W,1.0,0.0,Manchester Utd,0.7,...,0.0,0.0,0.0,2018,West Bromwich Albion,1,0,16,16,6
39,2018-04-21,12:30,Matchweek 35,Sat,Home,D,2.0,2.0,Liverpool,1.3,...,0.0,0.0,0.0,2018,West Bromwich Albion,0,1,14,12,5
40,2018-04-28,15:00,Matchweek 36,Sat,Away,W,1.0,0.0,Newcastle Utd,0.7,...,0.0,0.0,0.0,2018,West Bromwich Albion,1,0,17,15,5
41,2018-05-05,15:00,Matchweek 37,Sat,Home,W,1.0,0.0,Tottenham,1.6,...,0.0,0.0,0.0,2018,West Bromwich Albion,1,1,24,15,5
42,2018-05-13,15:00,Matchweek 38,Sun,Away,L,0.0,2.0,Crystal Palace,0.2,...,1.0,0.0,0.0,2018,West Bromwich Albion,0,0,8,15,6

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [21]:
train = matches[matches["date"] < '2022-11-01']

In [22]:
test = matches[matches["date"] > '2022-09-01']

In [23]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [24]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [25]:
preds = rf.predict(test[predictors])

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
acc = accuracy_score(test["target"], preds)

In [28]:
acc

0.7105263157894737

In [29]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [30]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted   0   1
actual
0          81  13
1          31  27

In [31]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.675

In [32]:
grouped_matches = matches.groupby("team")

In [33]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [34]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [35]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2017-09-09,12:30,Matchweek 4,Sat,Home,W,5.0,0.0,Liverpool,2.4,...,12,5,1.666667,0.666667,17.333333,6.000000,18.566667,1.333333,0.000000,0.000000
5,2017-09-16,15:00,Matchweek 5,Sat,Away,W,6.0,0.0,Watford,3.3,...,15,5,2.666667,0.666667,17.000000,8.000000,16.733333,0.666667,0.000000,0.000000
7,2017-09-23,15:00,Matchweek 6,Sat,Home,W,5.0,0.0,Crystal Palace,4.5,...,15,5,4.333333,0.333333,19.666667,9.000000,15.800000,0.333333,0.333333,0.333333
9,2017-09-30,17:30,Matchweek 7,Sat,Away,W,1.0,0.0,Chelsea,0.9,...,17,5,5.333333,0.000000,21.666667,9.333333,14.900000,0.000000,0.333333,0.333333
10,2017-10-14,15:00,Matchweek 8,Sat,Home,W,7.0,2.0,Stoke City,3.8,...,15,5,4.000000,0.000000,23.000000,7.666667,16.233333,0.333333,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,2022-10-02,14:00,Matchweek 9,Sun,Home,W,6.0,3.0,Manchester Utd,3.2,...,14,6,3.333333,0.333333,15.333333,6.666667,17.000000,0.333333,0.000000,0.000000
12,2022-10-08,15:00,Matchweek 10,Sat,Home,W,4.0,0.0,Southampton,2.4,...,15,5,3.333333,1.333333,17.000000,6.666667,16.800000,0.666667,0.000000,0.000000
14,2022-10-16,16:30,Matchweek 11,Sun,Away,L,0.0,1.0,Liverpool,1.0,...,16,6,4.333333,1.000000,19.666667,8.000000,15.833333,0.333333,0.000000,0.000000
15,2022-10-22,15:00,Matchweek 13,Sat,Home,W,3.0,1.0,Brighton,1.6,...,15,5,3.333333,1.333333,19.666667,7.666667,15.500000,0.333333,0.000000,0.000000
17,2022-10-29,12:30,Matchweek 14,Sat,Away,W,1.0,0.0,Leicester City,1.0,...,12,5,2.333333,0.666667,15.333333,5.666667,15.766667,0.000000,0.333333,0.333333

In [36]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [37]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 4  2017-09-09  15:00   Matchweek 4  Sat  Home      W
                        6  2017-09-17  13:30   Matchweek 5  Sun  Away      D
                        8  2017-09-25  20:00   Matchweek 6  Mon  Home      W
                        10 2017-10-01  12:00   Matchweek 7  Sun  Home      W
                        11 2017-10-14  17:30   Matchweek 8  Sat  Away      L
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 9  2022-10-08  15:00  Matchweek 10  Sat  Away      L
                        10 2022-10-15  15:00  Matchweek 11  Sat  Home      W
                        11 2022-10-18  20:15  Matchweek 12  Tue  Away      L
                        12 2022-10-23  14:00  Matchweek 13  Sun  Home      L
                        13 2022-10-29  15:00  Matchweek 14  Sat  Away      D

                             gf   ga         opponent   xg  ...  hour  \
team                                                        ...
Arsenal                 4   3.0  0.0      Bournemouth  2.2  ...    15
                        6   0.0  0.0          Chelsea  1.4  ...    13
                        8   2.0  0.0        West Brom  2.2  ...    20
                        10  2.0  0.0         Brighton  2.4  ...    12
                        11  1.0  2.0          Watford  1.0  ...    17
...                         ...  ...              ...  ...  ...   ...
Wolverhampton Wanderers 9   0.0  3.0          Chelsea  1.1  ...    15
                        10  1.0  0.0  Nott'ham Forest  1.3  ...    15
                        11  1.0  2.0   Crystal Palace  0.8  ...    20
                        12  0.0  4.0   Leicester City  2.1  ...    14
                        13  1.0  1.0        Brentford  0.6  ...    15

                            day_code  gf_rolling ga_rolling sh_rolling  \
team
Arsenal                 4          5    1.333333   2.666667  17.666667
                        6          6    1.000000   1.666667  14.333333
                        8          0    1.000000   1.333333  12.000000
                        10         6    1.666667   0.000000  14.333333
                        11         5    1.333333   0.000000  17.000000
...                              ...         ...        ...        ...
Wolverhampton Wanderers 9          5    0.333333   1.666667   9.333333
                        10         5    0.000000   2.666667   9.666667
                        11         1    0.333333   1.666667  10.333333
                        12         6    0.666667   1.666667   8.666667
                        13         5    0.666667   2.000000  13.000000

                           sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Arsenal                 4     5.333333    18.133333    0.000000    0.000000
                        6     5.000000    16.766667    0.333333    0.000000
                        8     3.666667    16.566667    0.333333    0.000000
                        10    5.333333    17.400000    1.333333    0.333333
                        11    5.000000    18.333333    1.666667    0.333333
...                                ...          ...         ...         ...
Wolverhampton Wanderers 9     2.333333    18.033333    0.666667    0.000000
                        10    2.333333    18.566667    1.000000    0.000000
                        11    2.333333    17.633333    0.333333    0.333333
                        12    2.333333    15.866667    0.666667    0.333333
                        13    3.333333    16.266667    0.666667    0.333333

                            pkatt_rolling
team
Arsenal                 4        0.000000
                        6        0.000000
                        8        0.000000
                        10       0.333333
                        11       0.333333
...                                   ...
Wolverhampton Wanderers 9        0.000000
                        10       0.000000
                        11       0.333333
                        12       0.333333
                        13       0.333333

[3956 rows x 38 columns]

In [38]:
matches_rolling = matches_rolling.droplevel('team')

In [39]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2017-09-09,15:00,Matchweek 4,Sat,Home,W,3.0,0.0,Bournemouth,2.2,...,15,5,1.333333,2.666667,17.666667,5.333333,18.133333,0.000000,0.000000,0.000000
6,2017-09-17,13:30,Matchweek 5,Sun,Away,D,0.0,0.0,Chelsea,1.4,...,13,6,1.000000,1.666667,14.333333,5.000000,16.766667,0.333333,0.000000,0.000000
8,2017-09-25,20:00,Matchweek 6,Mon,Home,W,2.0,0.0,West Brom,2.2,...,20,0,1.000000,1.333333,12.000000,3.666667,16.566667,0.333333,0.000000,0.000000
10,2017-10-01,12:00,Matchweek 7,Sun,Home,W,2.0,0.0,Brighton,2.4,...,12,6,1.666667,0.000000,14.333333,5.333333,17.400000,1.333333,0.333333,0.333333
11,2017-10-14,17:30,Matchweek 8,Sat,Away,L,1.0,2.0,Watford,1.0,...,17,5,1.333333,0.000000,17.000000,5.000000,18.333333,1.666667,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,2022-10-08,15:00,Matchweek 10,Sat,Away,L,0.0,3.0,Chelsea,1.1,...,15,5,0.333333,1.666667,9.333333,2.333333,18.033333,0.666667,0.000000,0.000000
10,2022-10-15,15:00,Matchweek 11,Sat,Home,W,1.0,0.0,Nott'ham Forest,1.3,...,15,5,0.000000,2.666667,9.666667,2.333333,18.566667,1.000000,0.000000,0.000000
11,2022-10-18,20:15,Matchweek 12,Tue,Away,L,1.0,2.0,Crystal Palace,0.8,...,20,1,0.333333,1.666667,10.333333,2.333333,17.633333,0.333333,0.333333,0.333333
12,2022-10-23,14:00,Matchweek 13,Sun,Home,L,0.0,4.0,Leicester City,2.1,...,14,6,0.666667,1.666667,8.666667,2.333333,15.866667,0.666667,0.333333,0.333333
13,2022-10-29,15:00,Matchweek 14,Sat,Away,D,1.0,1.0,Brentford,0.6,...,15,5,0.666667,2.000000,13.000000,3.333333,16.266667,0.666667,0.333333,0.333333

In [40]:
matches_rolling.index = range(matches_rolling.shape[0])

In [41]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-11-01']
    test = data[data["date"] > '2022-09-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [42]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [43]:
precision

0.9803921568627451

In [44]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [45]:
combined

,actual,predicted,date,team,opponent,result
192,0,0,2022-09-04,Arsenal,Manchester Utd,L
193,1,1,2022-09-18,Arsenal,Brentford,W
194,1,1,2022-10-01,Arsenal,Tottenham,W
195,1,1,2022-10-09,Arsenal,Liverpool,W
196,1,1,2022-10-16,Arsenal,Leeds United,W
...,...,...,...,...,...,...
3951,0,0,2022-10-08,Wolverhampton Wanderers,Chelsea,L
3952,1,1,2022-10-15,Wolverhampton Wanderers,Nott'ham Forest,W
3953,0,0,2022-10-18,Wolverhampton Wanderers,Crystal Palace,L
3954,0,0,2022-10-23,Wolverhampton Wanderers,Leicester City,L
3955,0,0,2022-10-29,Wolverhampton Wanderers,Brentford,D

In [46]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {
    "Brighton and Hove Albion": "Brighton", 
    "Manchester United": "Manchester Utd", 
    "Newcastle United": "Newcastle Utd", 
    "Tottenham Hotspur": "Tottenham", 
    "West Ham United": "West Ham", 
    "Wolverhampton Wanderers": "Wolves"
} 

mapping = MissingDict(**map_values)

In [47]:
combined["new_team"] = combined["team"].map(mapping)

In [48]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [49]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-09-04,Arsenal,Manchester Utd,L,Arsenal,1,1,Manchester United,Arsenal,W,Manchester Utd
1,1,1,2022-09-18,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
2,1,1,2022-10-01,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
3,1,1,2022-10-09,Arsenal,Liverpool,W,Arsenal,0,0,Liverpool,Arsenal,L,Liverpool
4,1,1,2022-10-16,Arsenal,Leeds United,W,Arsenal,0,0,Leeds United,Arsenal,L,Leeds United
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,0,0,2022-10-08,Wolverhampton Wanderers,Chelsea,L,Wolves,1,1,Chelsea,Wolves,W,Chelsea
140,1,1,2022-10-15,Wolverhampton Wanderers,Nott'ham Forest,W,Wolves,0,0,Nottingham Forest,Wolves,L,Nottingham Forest
141,0,0,2022-10-18,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,1,Crystal Palace,Wolves,W,Crystal Palace
142,0,0,2022-10-23,Wolverhampton Wanderers,Leicester City,L,Wolves,1,1,Leicester City,Wolves,W,Leicester City
143,0,0,2022-10-29,Wolverhampton Wanderers,Brentford,D,Wolves,0,0,Brentford,Wolves,D,Brentford

In [50]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    50
0     1
Name: actual_x, dtype: int64

In [51]:
74/122

0.6065573770491803

In [52]:
matches.columns

Index(['date', 'time', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'sh', 'sot', 'dist', 'fk', 'pk', 'pkatt',
       'season', 'team', 'target', 'venue_code', 'opp_code', 'hour',
       'day_code'],
      dtype='object')

In [53]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-09-04,Arsenal,Manchester Utd,L,Arsenal,1,1,Manchester United,Arsenal,W,Manchester Utd
1,1,1,2022-09-18,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
2,1,1,2022-10-01,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
3,1,1,2022-10-09,Arsenal,Liverpool,W,Arsenal,0,0,Liverpool,Arsenal,L,Liverpool
4,1,1,2022-10-16,Arsenal,Leeds United,W,Arsenal,0,0,Leeds United,Arsenal,L,Leeds United
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,0,0,2022-10-08,Wolverhampton Wanderers,Chelsea,L,Wolves,1,1,Chelsea,Wolves,W,Chelsea
140,1,1,2022-10-15,Wolverhampton Wanderers,Nott'ham Forest,W,Wolves,0,0,Nottingham Forest,Wolves,L,Nottingham Forest
141,0,0,2022-10-18,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,1,Crystal Palace,Wolves,W,Crystal Palace
142,0,0,2022-10-23,Wolverhampton Wanderers,Leicester City,L,Wolves,1,1,Leicester City,Wolves,W,Leicester City
143,0,0,2022-10-29,Wolverhampton Wanderers,Brentford,D,Wolves,0,0,Brentford,Wolves,D,Brentford

In [54]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-09-04,Arsenal,Manchester Utd,L,Arsenal,1,1,Manchester United,Arsenal,W,Manchester Utd
1,1,1,2022-09-18,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
2,1,1,2022-10-01,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
3,1,1,2022-10-09,Arsenal,Liverpool,W,Arsenal,0,0,Liverpool,Arsenal,L,Liverpool
4,1,1,2022-10-16,Arsenal,Leeds United,W,Arsenal,0,0,Leeds United,Arsenal,L,Leeds United
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,0,0,2022-10-08,Wolverhampton Wanderers,Chelsea,L,Wolves,1,1,Chelsea,Wolves,W,Chelsea
140,1,1,2022-10-15,Wolverhampton Wanderers,Nott'ham Forest,W,Wolves,0,0,Nottingham Forest,Wolves,L,Nottingham Forest
141,0,0,2022-10-18,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,1,Crystal Palace,Wolves,W,Crystal Palace
142,0,0,2022-10-23,Wolverhampton Wanderers,Leicester City,L,Wolves,1,1,Leicester City,Wolves,W,Leicester City
143,0,0,2022-10-29,Wolverhampton Wanderers,Brentford,D,Wolves,0,0,Brentford,Wolves,D,Brentford

In [55]:
merged.describe

<bound method NDFrame.describe of      actual_x  predicted_x       date                   team_x  \
0           0            0 2022-09-04                  Arsenal
1           1            1 2022-09-18                  Arsenal
2           1            1 2022-10-01                  Arsenal
3           1            1 2022-10-09                  Arsenal
4           1            1 2022-10-16                  Arsenal
..        ...          ...        ...                      ...
139         0            0 2022-10-08  Wolverhampton Wanderers
140         1            1 2022-10-15  Wolverhampton Wanderers
141         0            0 2022-10-18  Wolverhampton Wanderers
142         0            0 2022-10-23  Wolverhampton Wanderers
143         0            0 2022-10-29  Wolverhampton Wanderers

          opponent_x result_x new_team_x  actual_y  predicted_y  \
0     Manchester Utd        L    Arsenal         1            1
1          Brentford        W    Arsenal         0            0
2          Tottenham        W    Arsenal         0            0
3          Liverpool        W    Arsenal         0            0
4       Leeds United        W    Arsenal         0            0
..               ...      ...        ...       ...          ...
139          Chelsea        L     Wolves         1            1
140  Nott'ham Forest        W     Wolves         0            0
141   Crystal Palace        L     Wolves         1            1
142   Leicester City        L     Wolves         1            1
143        Brentford        D     Wolves         0            0

                team_y opponent_y result_y         new_team_y
0    Manchester United    Arsenal        W     Manchester Utd
1            Brentford    Arsenal        L          Brentford
2    Tottenham Hotspur    Arsenal        L          Tottenham
3            Liverpool    Arsenal        L          Liverpool
4         Leeds United    Arsenal        L       Leeds United
..                 ...        ...      ...                ...
139            Chelsea     Wolves        W            Chelsea
140  Nottingham Forest     Wolves        L  Nottingham Forest
141     Crystal Palace     Wolves        W     Crystal Palace
142     Leicester City     Wolves        W     Leicester City
143          Brentford     Wolves        D          Brentford

[144 rows x 13 columns]>

In [56]:
merged.to_csv("ultra.csv")